const patronkaPage = {
    title: 'Studium Sylwetki Patrona',
    lead: 'Królowa Jadwiga Andegaweńska',

    body: [
        'Życie i panowanie Jadwigi Andegaweńskiej\n' +
        '\n' +
        '\n' +
        'Królowa Jadwiga Andegaweńska była córką Ludwika Węgierskiego, króla Węgier i Polski oraz Elżbiety Bośniaczki, królowej węgierskiej i niekoronowanej królowej polskiej, regentki Królestwa Węgier. Była ponadto wnuczką Karola Roberta i Elżbiety Łokietkówny, siostry Kazimierza Wielkiego\n' +
        '\n' +
        'Większość współczesnych badaczy przyjmuje, że przyszła na świat w dniu 18 lutego 1374 (jest to 12 lat później data jej ślubu z Władysławem Jagiełłą, a więc zgodnie z prawem musiała już wówczas mieć wiek sprawny, czyli właśnie 12 lat) roku, lub parę dni wcześniej. Prawdopodobnym miejscem jej narodzin był zamek w Wyszehradzie lub Budzie.\n' +
        '\n' +
        'Pochodziła z dynastii Andegawenów, będącej boczną linią francuskiej dynastii Kapetyngów.  Nazwa dynastii wzięła się od tytułu hrabiego Andegawenii (Anjou), noszonego przez założyciela dynastii – Karola – pogrobowego syna króla Francji, Ludwika VIII. Przedstawiciele Andegawenów panowali m.in. na Sycylii, Węgrzech, w Albanii i w Polsce. Ciekawostką jest, że w jednym z miast rodowej siedziby tej dynastii – Angers, od listopada 1939 do czerwca 1940 r. siedzibę miał Rząd Polski na Uchodźctwie.\n' +
        '\n' +
        'Jadwiga była najmłodszą, trzecią córką Ludwika Węgierskiego i Elżbiety Bośniaczki. Jadwiga posiadała dwie siostry, Katarzynę i Marię. Katarzyna w planach dynastycznych ojca wyznaczona była na królową Polski, jednak zmarła w wieku ośmiu lat. Po śmierci siostry, królową Polski miała zostać Maria, jednak stało się inaczej i to Jadwiga trafiła na polski tron, ze względu na to, że Maria była zaręczona z Zygmuntem Luksemburskim, którego panowie małopolscy absolutnie nie chcieli widzieć na polskim tronie.\n' +
        '\n' +
        'Jadwiga otrzymała imię najpewniej na cześć księżnej wrocławskiej Jadwigi Śląskiej lub księżnej kaliskiej i królowej Polski Jadwigi, żony Władysława Łokietka, a swojej prababki.\n' +
        '\n' +
        'Być może nosiła również drugie imię, słowiańskie - Draga. Imię Jadwiga mogła otrzymać zgodnie z życzeniem babki – Elżbiety Łokietkówny, która była szarą eminencją na dworze węgierskim i miała duży wpływ na swojego syna Ludwika Węgierskiego.\n' +
        '\n' +
        'Jadwiga odebrała bardzo staranne wykształcenie, od najmłodszych lat była przygotowywana do pełnienia roli królowej. Potrafiła czytać i pisać, znała języki obce: łacinę, niemiecki i francuski, a także podstawy polskiego. Wykazywała zainteresowanie nauką, muzyką i sztuką, a jako że wychowywała się na dworze w Budzie, miała ku temu wszelkie możliwości. Warto wspomnieć wpływ kultury francuskiej jak i włoskiej (szczególnie Neapolu) na rozwój dworu Andegawenów na Węgrzech.\n' +
        '\n' +
        'Gdy miała cztery lata, została zaręczona z ośmioletnim księciem austriackim Wilhelmem z dynastii Habsburgów w formule prawa kanonicznego „sponsalia de futuro”.Ta forma stosowana przez dynastie panujące w Europie pozwalała ona na uroczyste zaręczyny niepełnoletnich kandydatów, dzięki czemu możliwe było zawieranie przypieczętowanych małżeństwem sojuszy, bez względu na wiek potomków rodu. Po osiągnięciu wieku sprawnego (12 lat dla dziewcząt, 14 lat dla chłopców) przez zaręczonych, nie ponawiano już właściwej ceremonii ślubnej, a przypieczętowanie małżeństwa miało nastąpić poprzez jego konsumpcje. Nie były to jednak kontrakty nierozerwalne. W przypadku związku Wilhelma Habsburga i Jadwigi Andegaweńskiej  podpisano zobowiązanie według którego, strona zrywająca zaręczyny wypłaca stronie drugiej 200 tys. florenów w złocie. Była to wówczas suma zawrotna.\n' +
        '\n' +
        'Jadwiga nie od razu była kandydatką do polskiego tronu.  Jej matka, Elżbieta Bośniaczka, wdowa po Ludwiku Wielkim, który był królem Węgier i Polski, oba królestwa chciała oddać w ręce starszej córki – Marii, ale jak wspomniano wyżej panowie małopolscy nie mogli się zgodzić na Zygmunta Luksemburskiego, jak i na Wilhelma Habsburga. Regentka Elżbieta Bośniaczka zgodziła się wysłać Jadwigę do Krakowa dopiero po ciągnących się ponad rok negocjacjach, które były bliskie zerwania.  Do wyjazdu i koronacji Jadwigi, Elżbieta odnosiła się z tak wielką rezerwą, że nawet nie przekazała jej przechowywanych na Węgrzech polskich insygniów koronacyjnych.\n' +
        '\n' +
        'Jadwiga ostatecznie przy wielkim nacisku polskich elit (realna groźba zerwania unii z Węgrami) przybyła do Krakowa 13 października 1384 roku, a 16 października została koronowana na króla Polski.  Koronacja odbyła się w katedrze wawelskiej w trakcie specjalnej mszy świętej, w obecności dostojników Królestwa. Koronacji dokonał arcybiskup gnieźnieński - Bodzęta. Ponieważ do kraju nie wróciły insygnia Kazimierza Wielkiego i Ludwika Węgierskiego, berło i jabłko królewskie trzeba było wykonać na nowo.\n' +
        '\n' +
        'Jadwiga, która dotychczas żyła w rodzinnym dobrze znanym środowisku, została osamotniona, zdezorientowana, a skarbiec królewski świecił pustkami w stosunku do tego co było w posiadaniu dworu na Węgrzech. Nie znała jeszcze wówczas dobrze języka polskiego, jedynie jego podstawy, a członkowie rady koronnej, robili wszystko, żeby nie czuła się na Wawelu zbyt pewnie. Pozbawiono ją węgierskich opiekunek, dworzan i wychowawców, odsyłając ich wszystkich z powrotem na Węgry. Miała odtąd uczyć się wszystkiego od Polaków. Więź z domem zapewniał jej tylko dawny prywatny lekarz króla Ludwika, Jan Radlica, który zdążył awansować nie tylko do rangi kanclerza, ale też biskupa krakowskiego. Został osobistym kapelanem, a zarazem najbliższym doradcą i opiekunem młodziutkiej władczyni. Jadwiga podarowała mu w 1384 roku własnoręcznie wyhaftowany zachowany do dziś pas liturgiczny.\n' +
        '\n' +
        'Państwem faktycznie rządzili panowie małopolscy, którzy pozostawali w kontakcie z matką Jadwigi, ale nie powołano formalnie urzędu regenta. Możnowładcy sami podejmowali decyzje nie pytając władczyni-dziecka o zdanie. We wcześniejszych negocjacjach z Elżbietą Bośniacką uzgodniono, że oddadzą dziewczynkę matce po koronacji, aby mogła dokończyć edukację i przygotować się do sprawowania rządów. Ale teraz, gdy Jadwiga Andegaweńska została już królem Polski, uznali, że jej wyjazd z Wawelu nie jest możliwy. Zgodnie z ówczesną praktyką podsuwali jej dokumenty, które ona miała zatwierdzać i ozdabiać swoją pieczęcią, ale nie wnikać w ich treść, co było oczywiście zgodne z ich interesem politycznym.\n' +
        '\n' +
        'Należy jednak wyraźnie podkreślić, że panowie małopolscy nie traktowali Jadwigi jako Andegawenki.  Była ona dla nich ostatnią przedstawicielką głównej linii rodu Piastów, który rządził nimi od ponad 400 lat. W dokumentach podkreślano, że jest „panią przyrodzoną”, jako prawnuczka Władysława Łokietka i wnuczka Elżbiety Łokietkówny.\n' +
        '\n' +
        'Panowie małopolscy zdecydowali się ostatecznie związać Polskę z Litwą i zaproponowali polską koronę wielkiemu księciu litewskiemu Jagielle, który miał przyjąć chrzest razem ze swoimi pogańskimi poddanymi. Tymczasem Jadwiga związana była zaręczynami z Wilhelmem Habsburgiem, którego popierał książę opolski Władysław Opolczyk. Miał on nawet próbować opanować zamek wawelski, chcąc przygotować dopełnienie małżeństwa. Kasztelan krakowski Dobiesław z  Kurozwęk nie wpuścił Austriaka do zamku. Jak podaje Jan Długosz młodziutka królowa chciała uciec z Wawelu do Wilhelma, którego ponoć pokochała poznając go osobiście podczas uczt w refektarzu klasztoru franciszkanów, ale powstrzymał ją podskarbi wielki koronny Dymitr z Goraja. Sam Wilhelm wraz ze świtą rezydował wówczas przy ulicy Legackiej (dziś Poselskiej), w domu Gniewosza z Dalewic, który był jego głównym zwolennikiem wśród panów małopolskich.\n' +
        '\n' +
        'Jadwiga ostatecznie jednak zgodziła się zostać żoną Jagiełły po długotrwałych negocjacjach i wizytach w Krakowie, nawet tak znakomitych posłów jak Skirgiełły, samego rodzonego brata Wielkiego Księcia Litwy. Publicznie odwołała swoje sponsalia z Wilhelmem. Jagiełło wystawił w tym czasie, dokładnie 14 VIII 1385 roku, słynny akt w Krewie, w którym m.in. zobowiązał się do zapłaty Habsburgowi owej sumy 200 tysięcy florenów za zerwanie sponsaliów. Jagiełło  przybył do Krakowa, gdzie 15 lutego 1386 roku przyjął chrzest i przybrał imię Władysław. Następnie 18 lutego zawarł w katedrze na Wawelu związek małżeński z Jadwigą. Jadwiga w chwili ślubu miała na pewno ukończone lat dwanaście, nie więcej niż trzynaście, a Jagiełło około trzydziestu. Dwa tygodnie później 4 III 1386 roku, w katedrze wawelskiej odbyła się uroczysta koronacja Władysława Jagiełły na króla Polski. Koronacji dokonał arcybiskup Bodzęnta w obecności legata pJadwiga była ponoć wysoką (175-180 cm), urodziwą dziewczyną o rudawych włosach. W Europie znana była nie tylko z urody, ale przede wszystkim z mądrej dyplomacji i głębokiej pobożności. Mimo bardzo młodego wieku podejmowała dojrzałe decyzje, choćby w sprawie swojego z Jagiełłą ślubu. Jej silna wiara, świadomość, że przed Bogiem (wprawdzie jako małe dziecko) poślubiła Wilhelma, a zapewne też uczucie, jakim go darzyła, nie pomagały jej w podjęciu decyzji o małżeństwie z tajemniczym księciem z pogańskiego kraju. Miała świadomość, że swoją decyzją spowoduje rozszerzenie chrześcijaństwa na setki tysięcy swoich nowych poddanych, a wszystko to być może za cenę osobistego szczęścia. Choć trudno w przypadku koronowanych władców epoki średniowiecza posługiwać się tego typu kategoriami moralno-emocjonalnymi. Raczej należy rozpatrywać tę w kwestie w aspekcie poczucia obowiązku i odpowiedzialności Jadwigi, która od wczesnego dzieciństwa miała świadomość swojej wyjątkowej roli do spełnienia. W rozumieniu i odpowiednim wypełnianiu swojego powołania, jakim było królowanie nad rzeszami poddanych, pomagała kontemplacja Stwórcy, który oddał swoje życie „za wielu”. Długie godziny spędzała na modlitwie. Klęczała przed wykonaną z lipowego drewna dwumetrową figurą Chrystusa Ukrzyżowanego w katedrze wawelskiej, nazywanego dzisiaj Czarnym Krucyfiksem, czekając na znak z Nieba. Miała ponoć usłyszeć słowa "Czyń, co widzisz".\n' +
        '\n' +
        'W 1387 roku Jadwiga stanęła na czele wyprawy rycerstwa polskiego, której celem była rewindykacja zajętej przez Węgrów Rusi Czerwonej. Potwierdziła też przywileje dla Lwowa, gwarantując mu prawo składu, a hospodar mołdawski Piotr I złożył jej tam hołd lenny. Aby utrzymać dobre stosunki z Węgrami, zaprzestała używania tytułu królowej Węgier, choć się go nie zrzekła. Wraz z mężem spotkali się z Zygmuntem Luksemburskim, który odstąpił dożywotnio Jagielle swoje prawa do Rusi Halickiej, a Jagiełło zrezygnował ze zwierzchnictwa nad Mołdawią i Podolem. Podpisano układ pokojowy na 16 lat. Pozwolił on Polsce wysunąć roszczenia wobec Zakonu krzyżackiego dotyczące zwrotu ziemi dobrzyńskiej. Odbył sie zjazd z udziałem wielkiego mistrza Konrada von Jungingena, na którym krzyżacy nie wyrazili zgody na oddanie tego terenu.\n' +
        '\n' +
        'Jadwiga bardzo dbała o szerzenie wiary na Litwie. W tym celu zorganizowała specjalne kolegium przy Uniwersytecie w Pradze, w którym kształcili się przyszli litewscy księża. Oznacza to, że w końcu lat osiemdziesiątych XIV w. nie planowano jeszcze poważnego odnowienia Uniwersytetu w Krakowie, który zaprzestał działalności po śmierci Kazimierza Wielkiego. Królowa Jadwiga umiała także zjednywać sobie ludzi. Miała pogodzić skłóconych ze sobą Jagiellonów na Litwie znała się na polityce, spotykała się z władcami wrogich państw, prowadziła pertraktacje i uczestniczyła w uzgadnianiu warunków pokoju. Wielokrotnie korespondowała z Wielkimi Mistrzami Zakonu Krzyżackiego, którzy żalili się jej na działania Litwinów i wspieranie ich przez męża królowej Władysława Jagiełłę.\n' +
        '\n' +
        'Starała się bardzo dbać o poddanych, których dobro leżało jej na sercu. Fundowała szpitale i liczne kościoły, uposażała istniejące klasztory. Najbardziej znana jest legenda związana z budową kościoła na Piasku w Krakowie. Pewnego dnia królowa wizytowała budowę tego kościoła i zauważyła jednego bardzo zatroskanego pracownika. Spytała go o powód zmartwienia i dowiedziała się, że znalazł się on w bardzo trudnej sytuacji. Jego żona, matka trójki dzieci była bardzo chora, a on nie miał pieniędzy na leczenie jej. Królowa niewiele myśląc, oderwała od swoich bucików ozdobną klamrę wysadzaną drogimi kamieniami i podarowała mu ją. Odrywając klamrę oparła stopę na kamieniu pokrytym wapnem, na którym pozostał odcisk buta. Po wizycie królowej, murarz zauważył ten ślad stopy na kamieniu, ociosał kamień i wmurował go w ściany świątyni. Do dziś można podziwiać tę odciśniętą stopę. Otoczona kratą, widnieje w jednym z narożników kościoła Karmelitów na Piasku.\n' +
        '\n' +
        'Jadwiga zleciła pierwsze w historii naszego kraju tłumaczenie Księgi Psalmów na język polski. Szczęśliwie zachował się egzemplarz tego dzieła znany pod nazwą Psałterz floriański bądź Psałterz Jadwigi. Jego nazwa pochodzi od miejscowości w Austrii - Sankt Florian, gdzie w 1931 roku w imieniu polskiego rządu zakupił go Ludwik Bernacki, dyrektor lwowskiego Ossolineum. W czasie II wojny światowej Psałterz został wywieziony do Kanady, a do Warszawy powrócił po 28 latach i obecnie znajduje się w zbiorach specjalnych Biblioteki Narodowej w Warszawie.\n' +
        '\n' +
        'Była osobą niesłychanie religijną, bardzo dużo czasu spędzała na modlitwie, praktykowała umartwianie się.  Oprócz zlecenia tłumaczenia Księgi Psalmów, fundowała też tłumaczenia pism Ojców Kościoła dla katedry wawelskiej. Pragnęła, aby tam chwalono Boga psalmami, dlatego ustanowiła specjalne kolegium szesnastu psalterzystów, którzy dzień i noc śpiewali psalmy przed Najświętszym Sakramentem. Ufundowała także i częściowo sama wyhaftowała racjonał - element szaty liturgicznej, dla biskupów krakowskich. Racjonał zachował się do dziś i jest używany podczas największych uroczystości kościelnych w katedrze wawelskiej.\n' +
        '\n' +
        'Cały swój majątek ruchomy zapisała na rzecz odnowienia i rozbudowy Uniwersytet Krakowskiego. U papieża wyprosiła pozwolenie na utworzenie na Uniwersytecie Wydziału Teologicznego, co znacznie przyspieszyło ewangelizację na całym obszarze ogromnego królestwa ziem polskich, litewskich i ruskich. Posiadanie takiego wydziału bardzo podnosiło rangę uczelni, która od tej pory zaczęła liczyć się bardzo w Europie.\n' +
        '\n' +
        'W wieku 25 lat, 22 czerwca 1399 roku Jadwiga Andegaweńska urodziła córkę Elżbietę Bonifację. Córeczka niestety zmarła po trzech tygodniach, a cztery dni po śmierci córki - 17 lipca 1399 roku zmarła także Jadwiga. Nie wiadomo co było przyczyną śmierci królowej, przypuszcza się, że zmarła na gorączkę połogową. Wiadomo, że królowa była wysoką osobą o silnej budowie i bardzo wąskiej miednicy. Gdyby wówczas wykonywano cesarskie cięcia, to prawdopodobnie Jadwiga by przeżyła.\n' +
        '\n' +
        'Królowa Jadwiga została pochowana w katedrze wawelskie 19 lipca 1399 roku. Pochowano ją w bardzo skromnym grobie, być może w oczekiwaniu na rychłą kanonizację Jadwigi. Początkowo skromna płyta grobowca spoczywała po północnej stronie prezbiterium, obok ołtarza. Według źródeł z XVI wieku napis na grobie królowej brzmiał: "Gwiazda Polaków, tu spoczywa Jadwiga ich Królowa". Podczas przebudowy prezbiterium, pierwotna płyta nagrobna uległa zniszczeniu. W 1634 roku wykonano nową płytę memoratywną z czarnego marmuru, z nową inskrypcją, fundacji biskupa Piotra Gembickiego. Sarkofag królowej Jadwigi był kilkakrotnie otwierany. Pierwszy raz w XVII wieku, w czasie przebudowy katedry. W XIX wieku został otwarty w obecności Jana Matejki, który przygotowywał portrety polskich władców. Trumna zawierała kompletny szkielet i królewski płaszcz. Matejko wykonał szkic czaszki, po czym szczątki królowej umieszczono w miedzianej trumnie, a tę w większej dębowej, po czym grób ponownie zamurowano. Kolejne otwarcie grobu nastąpiło w 1949 roku, kiedy to naukowcy prowadzili badania szczątków królowej. Stwierdzono wówczas, że monarchini została prawdopodobnie pochowana ze swoją zmarłą trzy tygodnie wcześniej córeczką, której szkielet się nie zachował. Charakterystyczne było ułożenie postaci Jadwigi, zbliżone do jednego z boków trumny, co tłumaczono tym, że obok leżało ciało dziecka. Świadczyło to też o tym, że od dnia pogrzebu ciało nie było ruszane.\n' +
        '\n' +
        'W 1987 roku relikwie królowej Jadwigi umieszczono w mensie ołtarza z czarnym krucyfiksem, z którego według legendy przemówił do niej Chrystus. Osobisty, papieski relikwiarz świętej Jadwigi królowej znajduje się w zbiorach muzealnych Ośrodka Dokumentacji i Studium Pontyfikatu Jana Pawła II w Rzymie.\n' +
        '\n' +
        'Pierwsze próby wyniesienia na ołtarze Jadwigi podjął w 1426 roku arcybiskup gnieźnieński Wojciech Jastrzębiec, jednak zakończyły się one niepowodzeniem. Stolica Apostolska odpowiadała, że Polscy mają już jedną świętą Jadwigę (Jadwiga Śląska, żona Henryka Brodatego). Następnie w 1949 roku arcybiskup krakowski Adam Stefan Sapieha, zebrał materiały dotyczące przyszłej świętej i przesłał je do Rzymu. Tym razem również Stolica Apostolska nie zgodziła się na rozpoczęcie procedury beatyfikacyjnej. Dopiero Karol Wojtyła w 1974 roku wydał orzeczenie o istnieniu publicznego kultu oddawanego od "niepamiętnych czasów", co pozwoliło kardynałowi Franciszkowi Macharskiemu zwrócić się do Watykanu z prośbą o zatwierdzenie tego kultu. W 1979 roku Karol Wojtyła, już jako papież Jan Paweł II, na dwa dni przed pierwszą pielgrzymką do Polski, dokonał beatyfikacji bł. Jadwigi, poprzez zatwierdzenie jej publicznego kultu.\n' +
        '\n' +
        'Uroczystej kanonizacji świętej Jadwigi dokonał papież Jan Paweł II, 8 czerwca 1997 roku na uroczystej mszy świętej sprawowanej na krakowskich błoniach - odbyło się to w obecności około miliona wiernych. Ojciec Święty zakończył kazanie przywołując średniowieczny hymn nieszporny śpiewany współcześnie na rozpoczęcie roku akademickiego „Gaude Mater Polonia”. Była to pierwsza w dziejach kanonizacja na ziemi polskiej. Od dnia kanonizacji wspomnienie liturgiczne w Kościele katolickim obchodzone jest 8 czerwca.\n' +
        '\n' +
        'Święta Jadwiga jest patronką Inowrocławia, Tczewa, Nieszawy i Radomska. Polski kompozytor Karol Krupiński w 1814 roku poświęcił królowej Jadwidze operę "Jadwiga Królowa Polska", do libretta Juliana Ursyna Niemcewicza. Berło królowej Jadwigi, tzw. rektorskie, ze złoconego srebra, przechowywane jest obecnie w Collegium Maius Uniwersytetu Jagiellońskiego w Krakowie. Jabłko i berło królowej - drewniane, złocone insygnia grobowe, przechowywane są w katedrze na Wawelu.\n' +
        '\n' +
        'W ikonografii św. Jadwiga przedstawiana jest w stroju królewskim.  Jej atrybutem są buciki, co związane jest z legendą. Królowa Jadwiga wraz Władysławem Jagiełłą królowali prawie trzynaście lat. Jagiełło, mimo że po śmierci Jadwigi posiadał jeszcze trzy żony, do końca życia nosił podarowany mu przez nią pierścień, co świadczy o szczególnym przywiązaniu władcy do swojej pierwszej małżonki.\n' +
        '\n' +
        'Opracowanie Dr Kamil Świderski\n' +
        '\n' +
        '  ',

    ],
    highlights: ['Tożsamość szkoły', 'Historia', 'Oś czasu'],
    layout: 'article',
    firstBlockHeading: true,
    showHighlights: true,
    author: 'Opracowanie: dr Kamil Świderski',
    timelineImage: `${import.meta.env.BASE_URL}os-czasu-jadwiga.png`,
    timelineAlt: 'Oś czasu kultu i pamięci o królowej Jadwidze',
};
    export default patronkaPage;